version: '3'

services:
  web:
    build: .
    command: python3 mysite/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 3000:8000
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend:
    driver: bridge